### ISSUE TITLE
Achievement  [Guru of Drakuru] Cleansing Drak'tharon

### ISSUE THREAD

**Issue by AnetteHansen** [WoWManiaUK/Redemption#2239]
Hey

I made a github twice before about this achievement #1896 and #2024. Everyhing works except one thing. When Drakuru is done talking to LK he is suppose to get the yellow ? above his head, so you can talk to him, deliver the quest and get the achievement. But even after standing there for 10 mins the ? never shows. 

This video shows at the very end what i mean https://www.youtube.com/watch?v=6g5ClSM64ys

And this screenshot is after listening to the talk between Drakuru and LK. Still no ?appears  https://gyazo.com/8cdff0f741865b6e08171de9e1076a83

Can you guys have another look at this. Thank you

**Comment by fvicaria** [comment]
That was fixed and confirmed a while back in #2024

**Comment by WhitephoenixTheBunny** [comment]
indeed

**Comment by TheManiax** [comment]
Please recheck.
Needs to be fixed if it is bugged anyway.

**Comment by AnetteHansen** [comment]
All i can say is that i have done this twice since fix #2024 was released and i still dont have the achievement completed

**Comment by WhitephoenixTheBunny** [comment]
Can you give me the name and link of achievement please?

**Comment by TheManiax** [comment]
@WhitephoenixTheBunny 
http://www.wowhead.com/achievement=1596/guru-of-drakuru

**Comment by WhitephoenixTheBunny** [comment]
Working fine in dev. Please be sure to have both chain quest complete: Cleansing Drak'Tharon ( http://www.wow-mania.com/armory/?quest=12713 ) and Betrayal ( http://www.wow-mania.com/armory/?quest=12713 )

![dev](https://user-images.githubusercontent.com/31921098/36075337-4b137d72-0f45-11e8-989f-a25ecd25d5c8.jpg)

**Comment by AnetteHansen** [comment]
Then i need one of the GMs to look into my toon. Im standing infront of Stefan that gives to two quests and he dont have any for me. Im pretty sure i havedone them both, but i only have the Betrayel as green in my achievement book
https://gyazo.com/4d1ad8a26bd732f3b01e2d7a198ef3df

**Comment by fvicaria** [comment]
What is the char name? I will check when I have a chance.
