### ISSUE TITLE
[Quest] That's Abominable!

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2522]
[[That's Abominable!]](http://www.wow-mania.com/armory/?quest=13264)
[[That's Abominable!]](http://www.wow-mania.com/armory/?quest=13276)
[[That's Abominable!]](http://www.wow-mania.com/armory/?quest=13288)
[[That's Abominable!]](http://www.wow-mania.com/armory/?quest=13289)
**How it should work:**
Player has to kill [[Hulking Abomination]](http://www.wow-mania.com/armory/?npc=31140) in order to loot a [[Chilled Abomination Guts]](http://www.wow-mania.com/armory/?item=43966), which will be used as a reagent for [[Abomination Reanimation Kit]](http://www.wow-mania.com/armory/?item=43968), this will cast [[Summon Reanimated Abomination]](http://www.wow-mania.com/armory/?spell=59565)
Using the summoned [[Reanimated Abomination]](http://www.wow-mania.com/armory/?npc=31692), player should be able to use it as a pet, doing the normal commands (i.e. attack)
And the [[Reanimated Abomination]](http://www.wow-mania.com/armory/?npc=31692) should also be able to cast [[Burst at the Seams]](http://www.wow-mania.com/armory/?spell=59580) , [[Burst at the Seams:Bone]](http://www.wow-mania.com/armory/?spell=52516) , [[Explode Abomination:Bloody Meat]](http://www.wow-mania.com/armory/?spell=52523) to kill the NPCs required to get the quest done.
**How it works:**
The summoned [[Reanimated Abomination]](http://www.wow-mania.com/armory/?npc=31692) will not attack on command, nor the [[Explode Abomination:Bloody Meat]](http://www.wow-mania.com/armory/?spell=52523) will kill the NPCs, though the explosion hit will give credit to the player. 

------

What you need to fix is the  "attack" command and the  [[Explode Abomination:Bloody Meat]](http://www.wow-mania.com/armory/?spell=52523) , the quest will be way easier for low geared players which is intended to be.

**Comment by fvicaria** [comment]
Pretty sure it works.

**Comment by TheManiax** [comment]
It is doable with a work around, but not working as intended.
You can close if you don't think it worth working.

**Comment by fvicaria** [comment]
I will check. If it is just the spell I will pass to Keader. He loves it.

**Comment by Keader** [comment]
Fixed i think

**Comment by Keader** [comment]
I found some bugs on this today.
Someone can test if in Red this quest give credit (all 4 quests) when just kill monsters (without abomination)

**Comment by TheManiax** [comment]
Currently on Redemption,None gives credit if you kill adds without abomination.

**Comment by TheManiax** [comment]
[[Explode Abomination:Bloody Meat]](http://www.wow-mania.com/armory/?spell=52523) is fixed.
Attack command not fixed yet.
![image](https://user-images.githubusercontent.com/14857593/41330707-6155886e-6eea-11e8-986f-754d85e6bf02.png)

**Comment by TheManiax** [comment]
After the last fix, the quest is easier now, still not working as intended
But it was doable and it is doable
