### ISSUE TITLE
[Achievement] Call to Arms!

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#2764]
The achievement requires you to complete the daily battleground "Call to Arms" quests: http://www.wow-mania.com/armory/?achievement=908

You should take these quests from the Alliance Brigadier General (Alliance), but he offers no quests.
NPC: http://www.wow-mania.com/armory/?npc=15351#currency-for

I use the launcher and latest client version.

**Comment by wow-mania** [comment]
As per the link you mentioned the NPC does not off the quest, only ends it.

**Comment by NightSeekerr** [comment]
Well, you can see on WoWWiki or WoWHead that the NPC is supposed to give you these daily quests. I just wanted to link your own armory.

**Comment by GmSaintz** [comment]
Can we take another look into this please? There does appear to be an issue with getting the Call to Arms quests needed for the Achievement. Players do not get quest upon joining the Call to Arms Battlegrounds. 

Alliance Call to Arms Achievment ID: 908 http://www.wow-mania.com/armory/?achievement=908
Horde Call to Arms Achievement ID: 909 http://www.wow-mania.com/armory/?achievement=909

Players should get the Call to arms quest upon joining the call to arms BG, IF I remember correctly. IF they win, the quest will complete, and the player should need to return to either a Horde Warbringer(15350) at any Horde capital city, Wintergrasp, Dalaran, or Shattrath - OR - an Alliance Brigadier General(15351) at any Alliance capital city, Wintergrasp, Dalaran, or Shattrath for the reward.

Horde Warbringer - 15350 - http://www.wow-mania.com/armory/?npc=15350
Alliance Brigadier General - 15351 - http://www.wow-mania.com/armory/?npc=15351

Call to Arms quests needed for achievement: 
Horde - 
Call to Arms: Arathi Basin (11339) - http://www.wow-mania.com/armory/?quest=11339
Call to Arms: Alterac Valley (11340) - http://www.wow-mania.com/armory/?quest=11340
Call to Arms: Eye of the Storm (11341) - http://www.wow-mania.com/armory/?quest=11341
Call to Arms: Warsong Gulch (11342) -  http://www.wow-mania.com/armory/?quest=11342

Alliance - 
Call to Arms: Arathi Basin (11335) - http://www.wow-mania.com/armory/?quest=11335
Call to Arms: Alterac Valley (11336) - http://www.wow-mania.com/armory/?quest=11336
Call to Arms: Eye of the Storm (11337) - http://www.wow-mania.com/armory/?quest=11337
Call to Arms: Warsong Gulch (11338) -  http://www.wow-mania.com/armory/?quest=11338

**Comment by WhitephoenixTheBunny** [comment]
I will check it tomorrow

**Comment by squalllh1989** [comment]
Based on what i found, the daily call to arms quest has been removed in patch 3.3.3, player join the call to arms with the dungeon finder should have the quest automaticly accepted and automaticly complete it if they win, it should also count toward the achivement, but atm when you join the call to arms, you won't get the quest given to you, so no complete quest, lead to no achievement.

**Comment by squalllh1989** [comment]
daily quest is now given when join the call to arms bg through the queue, should be working alright now

**Comment by squalllh1989** [comment]
Nope this is not working, upon join the call to arms bg through the queue, you was given the daily call to arms quest, but after win the bg, the quest doesn't completed (tested with call to arms arathi basin)

**Comment by wow-mania** [comment]
Try again. The event must be on. I make it so it is on every hour.

**Comment by NightSeekerr** [comment]
This is not fixed completely.

https://i.imgur.com/uj0n6dU.jpg

As you can see on the screenshot, after completing the quest it requires me to return it to a Horde Warbringer and I am a Human Warrior. I still visited the Alliance Brigadier General but couldn't return the quest there.

**Comment by wow-mania** [comment]
There must be an issue with the quest id.
Send me the quest id you have in your log

**Comment by NightSeekerr** [comment]
I don't know what a quest id is, but I'm pretty sure I have http://www.wow-mania.com/armory/?quest=11342      in my quest log, while I should have http://www.wow-mania.com/armory/?quest=11338

Also, this is a problem all Alliances that I spoke with have.

**Comment by wow-mania** [comment]
I will check today and make sure there is no mistake in the code. Thanks a lot.

**Comment by NightSeekerr** [comment]
This is still not fixed. Here's a pic after we won Warsong Gulch:
 
![wowscrnshot_122818_230233](https://user-images.githubusercontent.com/30464528/50528112-16f60d00-0af5-11e9-9f8f-a350946a0972.jpg)

It still wants me to return it to a Horde Warbringer even though I'm Alliance and now it doesn't even show it as "Complete".

**Comment by wow-mania** [comment]
Found the issue. Should be OK now. 
Just drop the old quest since it was wrong.

**Comment by Dranah** [comment]
Quest now works as intended for Alliance chars too.
https://imgur.com/RSxr31y

**Comment by NightSeekerr** [comment]
Nope, still doesn't work properly. Issue now is this: 

![wowscrnshot_122918_201743](https://user-images.githubusercontent.com/30464528/50541170-82e57d80-0ba8-11e9-87c4-7ec397c3db32.jpg)

Quest is completed, all is good, but you cannot return it to an Alliance Brigadier General. When you click to talk to him he just opens the Commendations of Service trade window, which is weird because even on the map it shows he should be available for the quest: 

![wowscrnshot_122918_201758](https://user-images.githubusercontent.com/30464528/50541199-3a7a8f80-0ba9-11e9-9717-69016916bdf9.jpg)

**Comment by wow-mania** [comment]
It does. We tested. You have to remove all Call to Arms! quests you had and start new.

**Comment by NightSeekerr** [comment]
I had no Call to Arms quests in my quest log when I entered the WSG. I got this one when I joined the battleground.

**Comment by Dranah** [comment]
There was no mention of NPCs being broken too. I tested problem/fix with quest to be acquired and completed, and that works fine now.

PS: I just took a look at NPCs and they indeed don't offer you to hand in the quest. 
I found another issue as well, namely that on 3.3.3 Mark of Honor has been removed as a currency: http://wowwiki.wikia.com/wiki/Patch_3.3.3
We still get them from battlegrounds here. Now this may remain as a custom feature for all I care, but the odd part is that while the Horde Warbringer offers an extra quest https://www.wowhead.com/quest=8367/for-great-honor to turn these marks into honor on top of the commendations he's selling, the alliance version: https://www.wowhead.com/quest=8371/concerted-efforts is missing.
