### ISSUE TITLE
[Boss] Yogg-saron vol. II

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2796]
https://www.wowhead.com/npc=33288/yogg-saron

Another compilation of issues:

1) Wrong timers on Malady and Brain link
https://www.wowhead.com/spell=63830/malady-of-the-mind
https://www.wowhead.com/spell=63802/brain-link
This is a new bug, it used to work a couple months ago.
**How it should work:** Both spells should run on an individual 30sec cd and Sara uses them whenever they are available, so pretty much every 30sec. Death Ray being active should not interfere with the cast of these.
**How it works atm:** Malady appears to have a 20sec cd (is usually cast too frequently) other times its cast is delayed by the death lasers and is only cast after the lasers despawn. Brain Link seems non-existant, is not being cast most of the time.

2) Shattered Illusion's effect on tentacle spawns.
https://www.wowhead.com/spell=64173/shattered-illusion
**How it should work:** This effect stuns tentacles, Sara, and Yogg-saron, and should prevent any new tentacles from spawning from the moment the brainroom opens, until the Induce Madness finishes. It should however not reset timer on Crusher/Corruptor spawns, so as soon as Induce Madness ends, if they are off-cd, the next wave immediately spawns.
**How it works atm:** The stun effect works, however the spawn prevention only seems to apply to Crushers and Corruptors. Constrictor tentacles keep spawning. Also the cooldown on Crushers/Corruptors seems reset, sometimes they won't spawn for a whole minute after Induce Madness ended, so you just sit there with no tentacles.

3) Line of Sight in Brainroom
**How it should work:** When the illusion shatters and the invisible door opens, you should be able to start dpsing the brain as soon as its in range.
**How it works atm:** When you enter room and target brain, it keeps saying target isn't in line of sight in most parts of the brain room. You need to move around and position yourself until you finally find a spot that isn't LoS, losing precious time in the process. 

4) Exit portals cooldown
This seems to be an issue affecting most similar portal objects (in other raids too).
https://www.wowhead.com/object=194625 and all shared models
Portal use has some kind of global cooldown, when a player clicks and uses portal, it becomes unavailable to click to other players for about 1,5sec. 
In most raids its merely an annoyance, here, however, it can make or break the deal as you have very short time to DPS the brain and should only exit in the last second, and if you fail to do so (because the portal is used by other players), players go Insane, and is most likely a wipe.
**How it should work:** multiple players inside brain room should be able to click the same exit portal at the same time.

5) Tentacle Corpses dont despawn
**How it works:** When you kill any tentacle outside during phase2, their corpse stays there. This creates visual mess on the floor, making some effects more difficult to see, and confuses targeting macros.
**How it should work**: You can see on tankspot videos that as soon as a tentacle is killed, its body despawns entirely.

6) Guardian of Yogg Saron (phase1) explosion
Shadow Nova https://www.wowhead.com/spell=62714/shadow-nova
**How it works atm:**
This effect is currently capable of missing, and sometimes doing double damage on Sara.
Note, I am aware that debuff on players can result in a player taking double damage, however Sara has no such debuff, and she sometimes loses 50k health instead of 25k.
Here is a screenshot of log showing the Nova miss: https://imgur.com/B0XlZYR
How it should work: it should deal 25k~ shadow damage to all nearby units, never miss, nor hit for double on Sara

**Comment by squalllh1989** [comment]
Confirm these thing:
- Brain Link seems non-existant, is not being cast most of the time.
- Portal use has some kind of global cooldown, when a player clicks and uses portal, it becomes unavailable to click to other players for about 1,5sec.

**Comment by Keader** [comment]
Try now @Dranah 
About Line of Sight, i cant do nothing.
I checked sniffs, hitbox is correct, position is correct, everything is fine.
As spell, if i'm not just behind of Brain, i can hit normally.
As melee, i can hit oh edges normally

All other shits is fixed i think

**Comment by Dranah** [comment]
UPDATE:
- Guardians Shadow Nova still does double damage on Sara, you can do phase1 with 4-5 adds instead of 8 (need fix)
- Guardians Shadow Nova no longer appears to miss (fixed this part)
- Malady and Brain link are both cast once when p2 begins, but afterwards now only Brain Link is repeating at 30sec intervals, Malady is missing (need fix)
- Tentacle corpses now properly despawn (fixed)
- Exit portals still become passive for a second when a player uses them, other similar objects too (need fix)
- Induce Madness now properly prevents Constrictors from spawning and does not seem to reset the cooldown of others (fixed)
- About the line of sight issue, I took some screens for you:
https://imgur.com/Af6x1G8
https://imgur.com/Z0Ukryb
I believe the issue may have something to do with the boss falling into the floor, sometimes when I respawned the fight it looked like this:
https://imgur.com/AIWka3f

perhaps it's also halfway into the floor other times, just visually not

**Comment by Keader** [comment]
Try now @Dranah 
LoS issue i still cant reproduce.
And i cant make brain drop in ground.
Other issues should be fixed now.

**Comment by Dranah** [comment]
UPDATE:
- Guardians' shadow nova now does proper 25k damage every time. (fixed)
- Brain Link is cast periodically but currently only every 1minute, instead of 30s (need fix)
- Malady is now also cast periodically, but still too often, every 20sec, instead of every 30sec (need fix)
- Exit portal is no longer triggering cooldown when used (fixed)
- I guess LOS issue stays as-is, sad as its annoying af

**Comment by Keader** [comment]
@Dranah Fixed Malady.
But Brain Link i cant do nothing.
Right now, every time that spell is in inside cooldown, she will try again after 1 sec cast.

```cpp
case EVENT_BRAIN_LINK:
    if (me->GetSpellHistory()->HasCooldown(SPELL_BRAIN_LINK))
    {
        _events.Repeat(Seconds(1));
        return;
    }
    me->CastCustomSpell(SPELL_BRAIN_LINK, SPELLVALUE_MAX_TARGETS, 2);
    _events.ScheduleEvent(EVENT_BRAIN_LINK, Seconds(30), 0, PHASE_TWO);
   break;
```

**Comment by Dranah** [comment]
Spell timers are still wrong. Malady is running on 40sec ICD and Brain Link is still at 60.

**Comment by Keader** [comment]
Fixed and re-tested.
If needed, i record a video.

**Comment by Dranah** [comment]
**Malady of the Mind** is now cast at proper 30sec intervals however there is an issue with the effect itself: At the initial cast, the 3% sanity reduction is not cast on the target of fear, but other nearby raid member(s) instead. You can see several missiles flying to several targets when Malady is cast.
When the effect jumps, the fear+sanity reduction are properly applied together to the new target.
How it should work: at the initial cast, the 3% sanity reduction should apply to the target that receives the fear.

**Brain Link**s are working until the first two casts (30s between them), but then it switches to 1minute interval after. Also while it properly links your chars if you test with 2 toons, testing with 3 and 4 the cast has simply no effect, no beam to connect any players, no debuff , nothing.

**Comment by Keader** [comment]
I cant confirm that issue with cooldown.
To me, still work in 30 sec each cast (brain link)

```
Brain link 56:43
Malady: 56:49

Brain link 57:13
Malady: 57:19

Brain link: 57:43
Malady: 57:49

Brain Link: 58:13
Malady: 58:22
```

About Malady the problem is new
Fixed it too.
Brain link issue is new too
Both fixed i belive.
If you want, i can put a comment on events, and you can check cooldowns.

**Comment by Keader** [comment]
Not reverted, looks like a new bug o.O
Check if is fixed @Dranah

**Comment by Dranah** [comment]
Nope, still double damage.
According to combat log, when the add dies, he casts a nova which hits both the players and Sara and then casts another nova (at same moment) which hits only Sara.
So it looks more like double cast, instead of double damage simply.

**Comment by Keader** [comment]
Looks fixed to me @Dranah 

```
Keader has slain Guardian of Yogg-Saron!
Guardian of Yogg-Saron casts Shadow Nova.
Guardian of Yogg-Saron's Shadow Nova hits Keader for 19081 Shadow.(19081 Resisted)
Guardian of Yogg-Saron casts Shadow Nova.
Guardian of Yogg-Saron's Shadow Nova hits Sara for 25000 Shadow.
Guardian of Yogg-Saron died.
```

**Comment by Dranah** [comment]
Nope still not.
+ The spell is also capable of missing. That was also fixed before and is now back.

**Comment by Dranah** [comment]
Works fine on both difficulties now.
