### ISSUE TITLE
[Quest/Item] Flare Gun scaling with SP

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#3585]
**Links:**
http://www.wow-mania.com/armory/?quest=9711
http://www.wow-mania.com/armory/?npc=17664
provided item: http://www.wow-mania.com/armory/?item=24278

**What is Happening:**
When completed at high level, using the provided item on Matis seems to cause damage.  This kills him instantly, meaning the summoned NPCs have no chance to capture him.
This means the quest cannot complete, since the NPC have no target to capture.

**What Should happen:**
Using the Flare Gun provided should not cause any damage to Matis, allowing the NPC to "capture" Matis.

**Comment by wow-mania** [comment]
Quest works just fine. I have tried it with my level 80. If you attack the NPC and kill him that is another matter. I may reduce a bit the damage for the helper NPC but not much.

**Comment by jarvik76** [comment]
Please see this video, I have tried several times again this morning.  All I literally do is use the item, and the Matis instantly dies.  Quest does not complete.
https://youtu.be/ATZ2UtDCOtU

**Comment by Dranah** [comment]
I can reproduce this.
The quest item http://www.wow-mania.com/armory/?item=24278 seems to scale with spell power.
Its damage is not displayed anywhere on the logs or recount, but it deals increasing damage if you equip gear with SP.
While you can complete the quest just fine if you strip naked, we can't possibly expect the average newbs to figure this, so it should be fixed.

**Comment by wow-mania** [comment]
DO not reopen please I did the quest twice without a problem with a low level and a 80

**Comment by Dranah** [comment]
Did you test with a geared spellcaster?

**Comment by jarvik76** [comment]
This is not due to the toon being 80, it is due to being 80 as a spellcaster.  The item is still an issue as it scales with spellpower, and it should not.

**Comment by jeyrella** [comment]
This has regressed.
https://youtu.be/Jh-G964i3vM

**Comment by Rushor** [comment]
spell bonus removed
