### ISSUE TITLE
[Quest] {mount name} replacement quest should not be available

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4116]
There is several quests, near Riding Trainers at Kalimdor and Eastern Kingdom, that where removed on sooner expansion
They require "ancient" mounts, example:
At Darnassus:

![image](https://user-images.githubusercontent.com/31921098/74142607-2947e300-4bf1-11ea-9087-b733594913c5.png)
![image](https://user-images.githubusercontent.com/31921098/74142616-2e0c9700-4bf1-11ea-9dfc-c963560bdadf.png)

The "requirement" is now an added mount, sold at mall
Was removed at patch 1.4

Quest list:
https://www.wow-mania.com/armory/?search=replacement
![image](https://user-images.githubusercontent.com/31921098/74142930-cacf3480-4bf1-11ea-8d09-bed20b40eea9.png)

the quests should be removed

**Comment by Kitzunu** [comment]
I have a fix, will add when I am home in 30-35 minutes 🖤

**Comment by Kitzunu** [comment]
Fixed

**Comment by WhitephoenixTheBunny** [comment]
@Kitzunu add those https://www.wow-mania.com/armory/?search=exchange

**Comment by Kitzunu** [comment]
Ok, now these are all added 7671,7675,7664,7672,7665,7676,7677,7674,7673,7678

**Comment by WhitephoenixTheBunny** [comment]
okay, I just found that two NPC still have the quests:

https://www.wow-mania.com/armory/?npc=3362#starts
https://www.wow-mania.com/armory/?npc=3685#starts

those 2 quest should be removed aswell

(confusion was made due to quests have diferent name... my bad in here!)

**Comment by Rushor** [comment]
fixed / removed

**Comment by WhitephoenixTheBunny** [comment]
Fixed, no more quests

![image](https://user-images.githubusercontent.com/31921098/155327747-71a4fec4-baae-4ef3-a27a-2a4fa193679b.png)

![image](https://user-images.githubusercontent.com/31921098/155327931-33a7fd6b-4cf0-41b8-9832-af89d37f78d9.png)
