### ISSUE TITLE
[Quest] The Stones That Bind Us

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4972]
**Links:** http://www.wow-mania.com/armory?quest=2681

**What is Happening:** Same issue as in #3577. The stones will disappear after the channeled cast but the servants will still be there and in combat. Occurrence i would say is the same as mentioned there, about 40% of the time it happens. Another thing that seems to be troubling this quest is that the servants and the stones don't have the same respawn timer. So those where the stone didn't bug out and servants got killed will have the servants respawned after certain time but the stones will be missing.

**What Should happen:** After the stone was clicked and channel was complete, the servants should die and give credit to the quest. At the same time, servants should have the same respawn timer as the stones as without the stones this quest cannot be completed.

**P.S. This is not a range issue as suggested by @Rushor in the original post, as the servants were majorly killed right next to the stone.**

**Comment by Rushor** [comment]
checking

**Comment by Rushor** [comment]
hmm for me everything worked - but my range fix somehow got reverted. need to adjust that

**Comment by Rushor** [comment]
yes indeed, sometimes the stones do not kill the servants and sometimes the stones do not get clickable once severant reaches low hp.

should both be finally fixed now.

concerning the respawn. AS-IS. People need to check first if there is a servant and a stone close together.

**Comment by Oganku** [comment]
Always getting credit, but about half the time I'm getting double the credit for one crystal use. @Rushor

**Comment by Rushor** [comment]
try now pls - only one credit upon object usage should be given

**Comment by Oganku** [comment]
https://imgur.com/a/A8hJOH8

Still getting double credits, range still good.

**Comment by Rushor** [comment]
hmm really strange, i still cannot see or reproduce :o is that always happening?

**Comment by Oganku** [comment]
When I recorded that, it happened 3 times in a row. It seems to have a small internal CD, so that if I do 2 mobs too quickly, one will be double, and the other will be fine, but then the next one will again be doubled. I tried with 2 different characters and different stones/mobs and it always happens for some reason.

**Comment by Rushor** [comment]
So you fighted 2 servants at the same time?

**Comment by Oganku** [comment]
No, I would always only fight one at a time.

**Comment by bLeyaa** [comment]
Any updates? 😋

**Comment by Rushor** [comment]
some more adjustments done - pls try now. it should only handle the credit for one time in a row now.

please make sure to have the quest only 1 time in questlog aswell

**Comment by svijetlo** [comment]
i did it just fine get mob , dmg it to low hp he will be stuck at 1% use stone stone will be gone after channeling and mob die you get credit in quest
