### ISSUE TITLE
[Quest] Ruuna's Request – available too early

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6121]
When I came to [Ruuna](https://www.wowhead.com/wotlk/npc=27581/ruuna-the-blind) to hand in the quest [Ruuna the Blind](https://www.wowhead.com/wotlk/quest=12425/ruuna-the-blind), she had quest [Ruuna's Request](https://www.wowhead.com/wotlk/quest=12328/ruunas-request) already available, before I handed in the quest. So it seems this quest is also missing some prerequisites, as to how much earlier it is available I can't say.

This quest should be available only after handing in the quest [Ruuna the Blind](https://www.wowhead.com/wotlk/quest=12425/ruuna-the-blind), which is also available too early.

To get to this quest, player should do the quests as follows:
[The Conqueror's Task](https://www.wowhead.com/wotlk/quest=12468/the-conquerors-task) → [A Show of Strength](https://www.wowhead.com/wotlk/quest=12257/a-show-of-strength) + [The Flamebinders' Secrets](https://www.wowhead.com/wotlk/quest=12256/the-flamebinders-secrets) → [The Thane of Voldrune](https://www.wowhead.com/wotlk/quest=12259/the-thane-of-voldrune) → [My Enemy's Friend](https://www.wowhead.com/wotlk/quest=12412/my-enemys-friend). All this works
During My Enemy's Friend [Mikhail's Journal](https://www.wowhead.com/wotlk/item=37830/mikhails-journal) drops providing [quest ](https://www.wowhead.com/wotlk/quest=12423/mikhails-journal) with the same name.
→ →
[Mikhail's Journal](https://www.wowhead.com/wotlk/quest=12423/mikhails-journal) → [Gorgonna](https://www.wowhead.com/wotlk/quest=12424/gorgonna) → [Tactical Clemency](https://www.wowhead.com/wotlk/quest=12422/tactical-clemency)
→ Completing Tactical Clemency opens quest [Ruuna the Blind](https://www.wowhead.com/wotlk/quest=12425/ruuna-the-blind) which opens [Ruuna's Request](https://www.wowhead.com/wotlk/quest=12328/ruunas-request).

**Comment by Maine1** [comment]
Mikhail's journal is a series of 3 quests in total that only has 3 in the series even on wowhead 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/40ab419a-3795-4e1d-8d8a-2ad172e0823d)
Ruuna the Blind is a series of 4 quests only and doesn't say it requires Tactical Clemency for this to be available
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/92a9b5f2-7100-4e5f-9906-fdccd13c51ed)
Ruuna's request also does not require Ruuna the Blind to be completed in order to collect it according to wowhead also 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/e265224d-1c67-476b-8cc0-19522f2982e1)

**Comment by Maine1** [comment]
This quest becomes available after Tactical Clemency as displayed in Screenshot and requires other quests to be completed
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/99f31e14-65da-4a6d-ac02-927d76bb9d3c)

From my findings and research this looks like its working as intended and Blizzlike

**Comment by Maine1** [comment]
@Greywolf59 If you check your own links provided you will notice the above quests which you say are fine it does state they require the other quests and unlock further quests. The quests where you state the issue is. They don't say anything about requirement of previous quests to be completed :)

**Comment by Maine1** [comment]
@Rushor Quest https://www.wowhead.com/wotlk/quest=12328/ruunas-request Shouldn't be available before completing this series ![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/817169e7-189a-4f0a-a5df-7a1c8db9be2e) I have checked this and Ruuna's request is infact available before you acquire Mikhail's journal which is wrong

Please check this for alliance and horde side quests

**Comment by Lumber-Jack-2** [comment]
quest [12328](https://www.wowhead.com/wotlk/quest=12328/ruunas-request) will now only be available if quest 12422 is rewarded

**Comment by Echinaceax** [comment]
> quest [12328](https://www.wowhead.com/wotlk/quest=12328/ruunas-request) will now only be available if quest 12422 is rewarded

Not fix for me (not offered [12328](https://www.wowhead.com/wotlk/quest=12328/ruunas-request) )


completed 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0caabafb-342c-4c3d-81ed-3657728011c2)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/00c5f3cd-5f9e-4553-bc42-2db67ae097b8)

done from this order 

H [15-30] [Mikhail's Journal](https://wowpedia.fandom.com/wiki/Mikhail%27s_Journal_(quest))
H [15-30] [Gorgonna](https://wowpedia.fandom.com/wiki/Gorgonna_(quest))
H [15-30] [Tactical Clemency](https://wowpedia.fandom.com/wiki/Tactical_Clemency)
H [15-30] Ruuna the Blind

Note: this check was done from Horde

**Comment by Lumber-Jack-2** [comment]
updated it so Ruuna's Request is now only available after Ruuna the Blind is rewarded

**Comment by Echinaceax** [comment]
Test2, 2nd char 2nd fix ...no quest offered same as before @Rushor 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/15ff2019-df79-4d72-92b1-3580ef15add5)

@Maine1 
can you see if it does for you?

**Comment by Maine1** [comment]
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/7b21fca8-dc6d-4964-9087-664d24fa9023)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/2d3fea3e-ddb8-48fb-bb8b-1dc17cb18ea9)
Works for me after Ruuna the Blind handed in

**Comment by GMZinius** [comment]
Due to multiple tickets this quest for the horde has been redone as it wasn't fixed fully for horde
All is fixed now
